In [1]:
import pandas as pd
import numpy as np
import requests
import sys

# Google API Key
from config import gkey

In [2]:
fastfood_us_df = pd.read_csv("fastfood_restaurant_review.csv")

In [3]:
fastfood_us_df.head()

,name,country,latitude,longitude,Street Adress,price_level,rating,user_ratings_total
0,Sonic Drive-In,US,29.814697,-90.814742,"800 N Canal Blvd, Thibodaux, LA 70301",1.0,4.3,479.0
1,Taco Bell,US,35.803788,-83.580553,"206 Wears Valley Rd, Pigeon Forge, TN 37863",1.0,3.3,1029.0
2,Arby's,US,35.782339,-83.551408,"3652 Parkway, Pigeon Forge, TN 37863",1.0,3.9,1620.0
3,Steak 'n Shake,US,33.562738,-84.321143,"2118 Mt Zion Parkway, Morrow, GA 30260",1.0,3.4,5287.0
4,Wendy's,US,42.368823,-83.138251,"9768 Grand River Ave, Detroit, MI 48204",1.0,3.6,1560.0

In [4]:
fastfood_us_df.dropna()

,name,country,latitude,longitude,Street Adress,price_level,rating,user_ratings_total
0,Sonic Drive-In,US,29.814697,-90.814742,"800 N Canal Blvd, Thibodaux, LA 70301",1.0,4.3,479.0
1,Taco Bell,US,35.803788,-83.580553,"206 Wears Valley Rd, Pigeon Forge, TN 37863",1.0,3.3,1029.0
2,Arby's,US,35.782339,-83.551408,"3652 Parkway, Pigeon Forge, TN 37863",1.0,3.9,1620.0
3,Steak 'n Shake,US,33.562738,-84.321143,"2118 Mt Zion Parkway, Morrow, GA 30260",1.0,3.4,5287.0
4,Wendy's,US,42.368823,-83.138251,"9768 Grand River Ave, Detroit, MI 48204",1.0,3.6,1560.0
...,...,...,...,...,...,...,...,...
9296,Pizza Hut,US,36.078802,-80.387508,"5062 Styers Ferry Rd, Lewisville, NC 27023",1.0,3.6,230.0
9297,Pizza Hut,US,36.117563,-80.316553,"3460 Robinhood Rd, Winston-Salem, NC 27106",2.0,4.5,387.0
9298,Pizza Hut,US,36.077718,-80.176748,"3069 Kernersville Rd, Winston-Salem, NC 27107",1.0,4.6,1488.0
9299,Pizza Hut,US,36.111015,-80.089165,"838 S Main St, Kernersville, NC 27284",1.0,3.2,644.0
9301,Pizza Hut,US,34.632778,-78.624615,"1405 W Broad St, Elizabethtown, NC 28337",1.0,3.7,314.0

In [5]:
fastfood_us_df.to_csv('fastfood_restaurant_review.csv', index = False)